[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
services = { path = "lib/application/services" }
actix-web = "4.4.0"
actix-multipart = "0.6.1"
env_logger = "0.10.0"
log = "0.4.20"
dotenv = "0.15.0"