version: '3'
services:
  postgres:
    # image: postgres:latest
    image: postgres:16-alpine # on Windows OS. See: https://codereviewvideos.com/postgres-16-docker-workaround-program-postgres-is-needed-by-initdb/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: diesel-demo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - custom-network

volumes:
  pg_data:

networks:
  custom-network: