name: Auto-formatting Rust files

on:
  push:

jobs:
  auto_formatting_and_linting:
    name: Auto-formatting and linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Auto-formatting Rust files
        uses: MGTheTrain/public-github-actions/.github/actions/auto-formatting-for-rust@main
        with:
          WORKING_DIRECTORY: ./
          GH_TOKEN: ${{ inputs.GH_TOKEN }}